[[problem]]
name = "hello"
dir = "hello"
id = "hello"

[[problem]]
name = "scan me"
dir = "scanme"
id = "scanme"

[[problem]]
name = "multiply me"
dir = "multiplyme"
id = "multiplyme"

[[problem]]
name = "if"
dir = "if"
id = "if"

[[problem]]
name = "loop"
dir = "loop"
id = "loop"

[[problem]]
name = "swap"
dir = "swap"
id = "swap"

[[problem]]
name = "string"
dir = "string"
id = "string"

[[problem]]
name = "malloc int"
dir = "mallocint"
id = "mallocint"